### ISSUE TITLE
May I ask what is the difference between DINOv2.new.cpy, DINOv2.self. py, and DINOv2.py in the CVCities main/cvcities base/backbones file? 

### ISSUE THREAD

**Issue by sugy0114** [GaoShuang98/CVCities#6]
May I ask what is the difference between DINOv2.new.cpy, DINOv2.self. py, and DINOv2.py in the CVCities main/cvcities base/backbones file? If I want to make changes to the network, which file should I modify it in？
Looking forward to your reply!

**Comment by GaoShuang98** [comment]
Hi, @sugy0114 , Dinov2_Self.Py is the real file, dinov2.new.cpy dinov2.py is useless, in the future I will clean up redundant files and code to make the overall structure clearer.
