### ISSUE TITLE
May I ask what Python environment configuration is required to reproduce this paper

### ISSUE THREAD

**Issue by sugy0114** [GaoShuang98/CVCities#7]
Looking forward to your reply!

**Comment by sugy0114** [comment]
> Did you train successfully？

No

**Comment by xsf777** [comment]
> > Did you train successfully？
> 
> No

Can you run calc_distance_cvcities.py(on 10 cities)?

**Comment by GaoShuang98** [comment]
Hi, @sugy0114 ,  I exported a requirements.txt file using pipreqs, and I hope this will assist you in replicating your code. See [requirements.txt](https://github.com/GaoShuang98/CVCities/blob/main/requirements.txt)
