### ISSUE TITLE
find a error and memory too small to calc_distance_cvcites on 10cities ,how to sovle?

### ISSUE THREAD

**Issue by xsf777** [GaoShuang98/CVCities#8]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

**Comment by xsf777** [comment]
File "/home/CVCities-main/CVCities-main/train/train_cvcities.py", line 491, in <module>
    train_dataloader.dataset.shuffle(sim_dict,
  File "/home/CVCities-main/CVCities-main/train/cvcities_base/dataset/cvcities.py", line 170, in shuffle
    near_similarity = similarity_pool[idx][:neighbour_range]  # 获取idx在similarity_pool中的邻居范围内的相似性
KeyError: 51854
4it [00:00, 20.62it/s]

**Comment by GaoShuang98** [comment]
Hi, if you can not calculate the distance of all 10 cities, please do not load the city data without calculating the distance when loading the data, otherwise thie error will be reported.
